export const kLogin = '/login'
export const kNotYet = '/*'
export const kIndex = '/'
export const kUserSet = '/user-manager/UserSet'
export const kContentManage = '/content/manage'
export const kContentAdd = '/content/add'
export const kContentEdit = '/content/edit'
export const KTypeManage = '/content/type'
